# Introduction {#sec-intro}

------------------------------------------------------------------------

Loneliness, social isolation, and social exclusion are significant challenges in our society as they can be major contributors to many mental and physical health problems [@hemberg2022; @entringer2020; @reinwarth2021; @qualter2015; @cacioppo2008]. The Covid-19 pandemic in particular has raised public awareness of the issue of loneliness, as many people have had to forgo social interactions due to containment measures. So far, social science research on loneliness has mainly focused on older people, while there is limited research on feelings of loneliness, social exclusion and isolation among adolescents and young adults [@verity2022; @hemberg2022]. My PhD project aims to fill this research gap and develop a better understanding of loneliness in young people, including the influence of media use. The impact of technology and social media on social isolation is an ongoing area of research that is constantly evolving. Studies have shown that excessive use of social media can have negative effects on the health of young people, but the use of social media is one of the main channels of communication [@smith2021]. On the other hand, social media communication has an impact on real life relationships (ibid.). Conversely, there is a risk that young people who have unequal access or suffer from social isolation or loneliness may not be able to use media in the same way as their peers who are not restricted [@sarmiento2020]. This leads to the overarching research question: **What impact do inequalities in access to, use of and outcomes from (social) media have on social exclusion, social isolation, and loneliness?**

Social exclusion refers to the process by which certain individuals or groups are excluded or marginalised from other members of society [@djouadi2021]. Socially excluded individuals often have limited access to education, health care and suffer from a lack of social support potential [@chakravarty2006]. Social exclusion goes beyond simple isolation and involves active exclusion from social opportunities, resources, and participation. Social isolation, on the other hand, refers to the lack of social contacts, interactions, or bonds with other people [@leigh-hunt2017]. This can be voluntary or involuntary. Thus, social exclusion aims at the active exclusion from social opportunities, while social isolation refers to the lack of interpersonal interaction and social ties. Loneliness, in contrast, is an emotional feeling that occurs when someone feels the absence of social ties or the lack of a deep connection to other people (ibid). Although loneliness and social isolation are related, they are not identical [@luhmann2016]. There are situations in which people do not feel lonely even when they are alone. In contrast, people can feel lonely even when they are in the company of others (ibid.).

In the following abstract, I will present three[\[1\]](#_ftn1) possible research projects that can contribute to my dissertation project, which can be primarily realized within the framework of the Youth Survey Luxembourg 2024.

[\[1\]](#_ftnref1) The first two proposals are already more or less set, and the third paper is selected from the remaining three proposals.
