# Access and use of (social) media {#sec-paper3}

------------------------------------------------------------------------

The fourth proposal aims to address the measurement of loneliness. One of the most commonly used measures of loneliness is based on the UCLA scale. The UCLA Loneliness Scale is an instrument used to measure loneliness in individuals. It was developed by Daniel Russell and Linda Cutrona at the University of California, Los Angeles (UCLA) [@russell1980]. The scale is available in different versions (3 items, 4 items, 8 items and 20 items) with different response options. There is a broad body of research on the validity of the different versions [@mund2022]. However, no scale has yet investigated the influence of the introductory text of the question. The above-mentioned survey YAC 2021 used the UCLA version as shown in @tbl-table1. The adaptation in the introductory text: "In the last 12 months" is not included in the original versions of the loneliness scale [@schomaker2022]. Also, most surveys and other studies do not use an introductory text with a time reference [@mund2022; @luhmann2016; @hawkley2016]. For example, the German SOEP uses "How often do you..." [@goebel2023]. This leads to the question: What is the influence of the requested observation period on the UCLA Loneliness Scale on the response behaviour of young people? In order to be able to answer this question, a survey experiment will be conducted within the framework of the Youth Survey Luxembourg 2024, in which respondents will be randomised to answer the YAC 2021 version or the treatment @tbl-table1. With the help of group comparisons and structural equation models, the influence of the treatment will then be measured.

| **YAC 2021 adaption of UCLA (4 Items)**                                                                  | **Treatment**                                                                                            |
|------------------------------------|------------------------------------|
| In the last 12 months, how often have you felt as described in each of the following statements?         | How often have you felt as described in each of the following statements?                        |
| I feel isolated from others                                                                              | I feel isolated from others                                                                              |
| I feel excluded                                                                                          | I feel excluded                                                                                          |
| I lack companionship                                                                                     | I lack companionship                                                                                     |
| I am no longer close to anyone                                                                           | I am no longer close to anyone                                                                           |
| a\. Never, b. Occasionally, c. Less than half the time, d. More than half the time, e. Most of the time. | a\. Never, b. Occasionally, c. Less than half the time, d. More than half the time, e. Most of the time. |

: Comparison of the measurement of loneliness UCLA adaptation and treatment scale {#tbl-table1} 